language: node_js
node_js:
  - "stable"
cache:
  directories:
    - ./notagame/node_modules
before_install:
  - cd notagame
script:
  - export PUBLIC_URL=$(echo $TRAVIS_REPO_SLUG | awk -F'/' '{OFS=""; print "https://",$1,".github.io/",$2}')
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./notagame/build
  on:
    branch: master
