language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd notagame
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./notagame/build
  on:
    branch: master
